# Use root/example as user/password credentials
version: '3.1'

networks:
  database:

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
        - database
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    networks:
        - database
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1234