# Use root/example as user/password credentials
version: '3.1'

networks:
    database:

services:

    mongo:
        image: mongo
        restart: always
        container_name: mongo
        networks:
            - database
        ports:
            - 27017:27017


    mongo-express:
        image: mongo-express
        restart: always
        container_name: mongo-express
        networks:
            - database
        ports:
            - 8081:8081
